[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:file-server]
command=/app/file-server
user=nobody
autostart=true
autorestart=true
priority=10
stopsignal=TERM
stopwaitsecs=60
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
